# Generated by Django 5.2.1 on 2025-05-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
