# Generated by Django 5.2.1 on 2025-05-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_students_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='age',
        ),
    ]
